server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Redirigir llamadas a las APIs hacia los backends
    location /api/ventas {
        proxy_pass http://BACKEND_VENTAS_HOST:8081/;
    }
    location /api/despachos {
        proxy_pass http://BACKEND_DESPACHOS_HOST:8082/;
    }
}